
export const CustomerTableData = [
    {
        date: "27/11/2022  4:13:00 PM",
        fullname: "Jenkins International Ltd.",
        purpose: "Cheque",
        type: "Debit",
        amount: "- ₦1,350",
        action: "Cheque",
    },
    {
        date: "27/11/2022  4:13:00 PM",
        fullname: "Jenkins International Ltd.",
        purpose: "Cheque",
        type: "Credit",
        amount: "- ₦1,350",
        action: "Cheque",
    },
    {
        date: "27/11/2022  4:13:00 PM",
        fullname: "Jenkins International Ltd.",
        purpose: "Cheque",
        type: "Credit",
        amount: "- ₦1,350",
        action: "Cheque",
    },
    {
        date: "27/11/2022  4:13:00 PM",
        fullname: "Jenkins International Ltd.",
        purpose: "Cheque",
        type: "Credit",
        amount: "- ₦1,350",
        action: "Cheque",
    },
    {
        date: "27/11/2022  4:13:00 PM",
        fullname: "Jenkins International Ltd.",
        purpose: "Cheque",
        type: "Debit",
        amount: "- ₦1,350",
        action: "Cheque",
    },
    {
        date: "27/11/2022  4:13:00 PM",
        fullname: "Jenkins International Ltd.",
        purpose: "Cheque",
        type: "Debit",
        amount: "- ₦1,350",
        action: "Cheque",
    },
    {
        date: "27/11/2022  4:13:00 PM",
        fullname: "Jenkins International Ltd.",
        purpose: "Cheque",
        type: "Credit",
        amount: "- ₦1,350",
        action: "Cheque",
    },
    {
        date: "27/11/2022  4:13:00 PM",
        fullname: "Jenkins International Ltd.",
        purpose: "Cheque",
        type: "Credit",
        amount: "- ₦1,350",
        action: "Cheque",
    },
    {
        date: "27/11/2022  4:13:00 PM",
        fullname: "Jenkins International Ltd.",
        purpose: "Cheque",
        type: "Credit",
        amount: "- ₦1,350",
        action: "Cheque",
    },
    {
        date: "27/11/2022  4:13:00 PM",
        fullname: "Jenkins International Ltd.",
        purpose: "Cheque",
        type: "Debit",
        amount: "- ₦1,350",
        action: "Cheque",
    },


]