
export const CustomerTableData = [
    {
        date: "13 July, 2021",
        fullname: "Samuel woodfree",
        purpose: "January Salary",
        type: "Credit",
        amount: "N44,345.00",
    },
    {
        date: "13 July, 2021",
        fullname: "BRT",
        purpose: "Transport",
        type: "Credit",
        amount: "N4,345.00",
    },
    {
        date: "13 July, 2021",
        fullname: "Kaj",
        purpose: "Office hangout",
        type: "Credit",
        amount: "N444,345.00",
    },
    {
        date: "13 July, 2021",
        fullname: "Tunde Kofo",
        purpose: "Food Delivery",
        type: "Debit",
        amount: "N4,345.00",
    },
    {
        date: "13 July, 2021",
        fullname: "Tunde Kofo",
        purpose: "Food Delivery",
        type: "Debit",
        amount: "N4,345.00",
    },
    {
        date: "13 July, 2021",
        fullname: "Samuel woodfree",
        purpose: "Food Delivery",
        type: "Debit",
        amount: "N4,345.00",
    },
    {
        date: "13 July, 2021",
        fullname: "Kaj",
        purpose: "Office hangout",
        type: "Credit",
        amount: "N444,345.00",
    },
    {
        date: "13 July, 2021",
        fullname: "BRT",
        purpose: "Transport",
        type: "Credit",
        amount: "N4,345.00",
    },
    {
        date: "13 July, 2021",
        fullname: "Tunde Kofo",
        purpose: "January Salary",
        type: "Credit",
        amount: "N44,345.00",
    },
    {
        date: "13 July, 2021",
        fullname: "Samuel woodfree",
        purpose: "Office hangout",
        type: "Debit",
        amount: "N44,345.00",
    },


]


export const AdminTableData = [
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Inactive",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Inactive",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Inactive",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Active",
    },
    {
        fullname: "Tope hope",
        roles: "Operation Manager",
        lastActive: "24 July 2021",
        status: "Inactive",
    },
]

export const CardTableData = [
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Virtual Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Prepaid Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Physical Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Virtual Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Prepaid Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Physical Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Virtual Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Prepaid Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Physical Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Virtual Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Prepaid Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Physical Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Virtual Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Prepaid Card",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        type: "Physical Card",
    },
]

export const CardDetailsData = [
    {
        title: "Mr",
        surname: "Bond",
        firstname: "James",
        othernames: "Joseph",
        gender: "Male",
        phonenumber: "0806xxxxx250",
        emailaddress: "yourmail@gmail.com",
        dateofbirth: "31-01-1992",
    },
]
export const AccountsTableData = [
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
    {
        fullname: "John Doe",
        email: "your@email.com",
        accountNo: "1234567890",
        date: "13 July 2021",
    },
]